
services:
  db:
    image: postgres:latest
    container_name: my_postgres_container
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - mynetwork

  web:
    build: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8020:8003"
    image: instagram
    container_name: instagram_container
    command: ["/wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8003"]
    depends_on:
      - db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  db_data: {}