# Generated by Django 4.2 on 2025-04-17 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_category_alter_post_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
