# Generated by Django 4.2 on 2025-04-25 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='commentreplay',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='created_time',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_time',
            new_name='created_at',
        ),
    ]
