# Generated by Django 4.2 on 2025-04-24 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_slug'),
        ('user', '0004_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, to='post.post'),
        ),
    ]
