# Generated by Django 4.2 on 2025-04-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_category_slug'),
        ('user', '0005_alter_profile_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='posts', to='post.post'),
        ),
    ]
